class AssetConst {
  const AssetConst._();

  static const String loginLogo = 'assets/images/logo.png';
  static const String youtube = 'assets/images/youtube.png';
  static const String youturbe = 'assets/images/youturb.png';
  static const String loginBG = 'assets/images/login_bg.png';
  static const String chutkiWithText = 'assets/images/Group 4.png';
  static const String rectangleTextfield = 'assets/images/Rectangle 4.png';
  static const String dial = 'assets/images/dial 1.png';
  static const String hide = 'assets/images/hide 1.png';
  static const String lock = 'assets/images/lock 1.png';
  static const String mPinAsset = 'assets/images/2 2.png';
  static const String forgetPasswordBG = 'assets/images/sd 2.png';
  static const String profile1 = 'assets/images/profile (2) 1.png';
  static const String profile2 = 'assets/images/cooperation 1.png';
  static const String registerBG = 'assets/images/register bg.png';
  static const String profileUser = 'assets/images/profile-user 1.png';
  static const String closedMail = 'assets/images/closed-mail 1.png';
  static const String refer = 'assets/images/refer 1.png';
  static const String lock5 = 'assets/images/lock 5.png';
  static const String location = 'assets/images/location 1.png';
  static const String district = 'assets/images/district (1) 1.png';
  static const String district1 = 'assets/images/district 1 (1).png';
  static const String house = 'assets/images/houses 1.png';
  static const String village = 'assets/images/village 1.png';
  static const String trainingBG = 'assets/images/trainingBG.png';
  static const String chutki = 'assets/images/chutki.png';
  static const String rewardChutki = 'assets/images/reward-points 1.png';
  static const String addWallet = 'assets/images/add-wallet 1.png';
  static const String coinWallet = 'assets/images/Group 27.png';
  static const String playIcon = 'assets/images/play-icon.png';
  static const String takseMall = 'assets/images/taksemall.png';
  static const String search = 'assets/images/search.png';
  static const String notification = 'assets/images/notification.png';
  static const String humburger = 'assets/images/hum-burger.png';
  static const String leader = 'assets/images/leaders.png';
  static const String question = 'assets/images/question.png';
  static const String wallet = 'assets/images/wallet.png';
}
